FROM cgr.dev/chainguard/python:latest-dev AS build
WORKDIR /app
RUN python3 -m venv venv
COPY requirements.txt requirements.txt
COPY app.py app.py
RUN venv/bin/pip install -r requirements.txt

FROM cgr.dev/chainguard/python:latest
COPY --from=build /app /app
WORKDIR /app

ENTRYPOINT ["/app/venv/bin/python"]
CMD ["app.py"]