apiVersion: v1
kind: ConfigMap
metadata:
  name: index-vars
data:
  MY_NAME: Frodo
  MY_ENV: "The Shire"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: envsubst
        image: localhost:5001/mynginx:5-init
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: index-vars
        volumeMounts:
        - name: html
          mountPath: /new-html
          readOnly: false
        command: ['sh', '-c', 'cat /index.html | envsubst | tee /new-html/index.html']
      containers:
      - name: nginx
        image: localhost:5001/mynginx:5-main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html
          mountPath: /var/lib/nginx/html/index.html
          subPath: index.html
          readOnly: true
      volumes:
      - name: html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer