FROM cgr.dev/chainguard/nginx:latest-dev
USER root
RUN apk add --no-cache gettext
USER 65532

COPY --chown=65532:65532 html /var/lib/nginx/html
COPY start.sh /start.sh
ENV MY_NAME="Default Name from Dockerfile"
ENV MY_ENV="Default Environment from Dockerfile"

ENTRYPOINT ["/start.sh"]